package_name: fraud_detection_model
training_data_file: data.csv
test_data_file: test.csv
target: isFraud
pipeline_name: fraud_detection_model
pipeline_save_file: fraud_detection_model_output_v
features:
  - type
  - amount
  - oldbalanceOrg
  - newbalanceOrig
unused_fields:
  - step
  - newbalanceDest
  - oldbalanceDest
  - nameOrig
  - nameDest
  - isFlaggedFraud
test_size: 0.2
random_state: 42

